spring:
  config:
    activate:
      on-profiles: dev
  datasource:
    url: jdbc:h2:file:./db/hrbank-db
    username: hrbank
    password: hrbank1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: false       # H2 콘솔 활성화
      path: /h2-console   # 접속 경로 지정 (기본: /h2-console)
  logging:
    level:
      org.hibernate.type: INFO
