spring:
  config:
    activate:
      on-profiles: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/hrbank
    username: hrbank
    password: hrbank1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

