spring:
  config:
    activate:
      on-profiles: dev
  datasource:
    url: jdbc:h2:tcp://localhost/~/hrbank
    username: hrbank
    password: hrbank1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.hibernate.type: INFO
